plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.1'
}

group = 'com.dxunvrs'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.github.cdimascio:dotenv-java:latest.release'

    implementation 'com.fasterxml.jackson.core:jackson-databind:latest.release'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-csv:latest.release'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:latest.release'
    implementation 'org.slf4j:slf4j-api:2.0.17'
    implementation 'ch.qos.logback:logback-classic:latest.release'

    implementation 'com.dxunvrs:common:1.0'

    implementation("com.squareup.okhttp3:okhttp:5.2.0")

    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
}

shadowJar {
    archiveClassifier.set('')
    archiveVersion.set('')

    manifest {
        attributes 'Main-Class': 'Main'
    }
}