plugins {
    id 'java'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '9.3.1'
}

group = 'com.dxunvrs'
version = '1.1'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:latest.release'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-csv:latest.release'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:latest.release'

    implementation 'org.jdbi:jdbi3-sqlobject:3.52.0'
}

shadowJar {
    archiveClassifier.set('')
}

publishing {
    publications {
        shadow(MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = project.version

            artifact shadowJar
        }
    }
    repositories {
        maven {
            name = "reposiliteRepository"
            url = "http://maven.dxunvrs.ru/releases"
            allowInsecureProtocol = true

            credentials {
                username = REPOSILITE_USER
                password = REPOSILITE_TOKEN
            }
        }
    }
}
